- name: C/C++ code linter (clang-tidy, clang-format, and cppcheck)
  uses: ArtificialAmateur/cpp-linter-action@0.01
name: C/C++ CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
